package com.zhongweixian.web.entity;

import java.io.Serializable;
import java.util.Date;

public class BotVideo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_message_video.id
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_message_video.cts
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    private Date cts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_message_video.channel
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    private String channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_message_video.chat_type
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    private String chatType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_message_video.chat_name
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    private String chatName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_message_video.from_url
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    private String fromUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_message_video.video_url
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_message_video.video_size
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    private Integer videoSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_message_video.video_cloud
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    private String videoCloud;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_message_video.hash_code
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    private String hashCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_message_video.from_uid
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    private String fromUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_message_video.from_user
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    private String fromUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_message_video.status
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_message_video
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_message_video.id
     *
     * @return the value of bot_message_video.id
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_message_video.id
     *
     * @param id the value for bot_message_video.id
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_message_video.cts
     *
     * @return the value of bot_message_video.cts
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public Date getCts() {
        return cts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_message_video.cts
     *
     * @param cts the value for bot_message_video.cts
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public void setCts(Date cts) {
        this.cts = cts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_message_video.channel
     *
     * @return the value of bot_message_video.channel
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_message_video.channel
     *
     * @param channel the value for bot_message_video.channel
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_message_video.chat_type
     *
     * @return the value of bot_message_video.chat_type
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public String getChatType() {
        return chatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_message_video.chat_type
     *
     * @param chatType the value for bot_message_video.chat_type
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public void setChatType(String chatType) {
        this.chatType = chatType == null ? null : chatType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_message_video.chat_name
     *
     * @return the value of bot_message_video.chat_name
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public String getChatName() {
        return chatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_message_video.chat_name
     *
     * @param chatName the value for bot_message_video.chat_name
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public void setChatName(String chatName) {
        this.chatName = chatName == null ? null : chatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_message_video.from_url
     *
     * @return the value of bot_message_video.from_url
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public String getFromUrl() {
        return fromUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_message_video.from_url
     *
     * @param fromUrl the value for bot_message_video.from_url
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public void setFromUrl(String fromUrl) {
        this.fromUrl = fromUrl == null ? null : fromUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_message_video.video_url
     *
     * @return the value of bot_message_video.video_url
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_message_video.video_url
     *
     * @param videoUrl the value for bot_message_video.video_url
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_message_video.video_size
     *
     * @return the value of bot_message_video.video_size
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public Integer getVideoSize() {
        return videoSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_message_video.video_size
     *
     * @param videoSize the value for bot_message_video.video_size
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public void setVideoSize(Integer videoSize) {
        this.videoSize = videoSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_message_video.video_cloud
     *
     * @return the value of bot_message_video.video_cloud
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public String getVideoCloud() {
        return videoCloud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_message_video.video_cloud
     *
     * @param videoCloud the value for bot_message_video.video_cloud
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public void setVideoCloud(String videoCloud) {
        this.videoCloud = videoCloud == null ? null : videoCloud.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_message_video.hash_code
     *
     * @return the value of bot_message_video.hash_code
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public String getHashCode() {
        return hashCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_message_video.hash_code
     *
     * @param hashCode the value for bot_message_video.hash_code
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public void setHashCode(String hashCode) {
        this.hashCode = hashCode == null ? null : hashCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_message_video.from_uid
     *
     * @return the value of bot_message_video.from_uid
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public String getFromUid() {
        return fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_message_video.from_uid
     *
     * @param fromUid the value for bot_message_video.from_uid
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public void setFromUid(String fromUid) {
        this.fromUid = fromUid == null ? null : fromUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_message_video.from_user
     *
     * @return the value of bot_message_video.from_user
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public String getFromUser() {
        return fromUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_message_video.from_user
     *
     * @param fromUser the value for bot_message_video.from_user
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public void setFromUser(String fromUser) {
        this.fromUser = fromUser == null ? null : fromUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_message_video.status
     *
     * @return the value of bot_message_video.status
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_message_video.status
     *
     * @param status the value for bot_message_video.status
     *
     * @mbg.generated Sat Jun 29 10:53:27 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "BotVideo{" +
                "id=" + id +
                ", cts=" + cts +
                ", channel='" + channel + '\'' +
                ", chatType='" + chatType + '\'' +
                ", chatName='" + chatName + '\'' +
                ", fromUrl='" + fromUrl + '\'' +
                ", videoUrl='" + videoUrl + '\'' +
                ", videoSize=" + videoSize +
                ", videoCloud='" + videoCloud + '\'' +
                ", hashCode='" + hashCode + '\'' +
                ", fromUid='" + fromUid + '\'' +
                ", fromUser='" + fromUser + '\'' +
                ", status=" + status +
                '}';
    }
}