package com.zhongweixian.web.mapper;

import com.zhongweixian.web.entity.BotVideo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface BotVideoMapper extends BaseMapper<BotVideo> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_message_video
     *
     * @mbg.generated Thu Jun 27 23:32:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_message_video
     *
     * @mbg.generated Thu Jun 27 23:32:58 CST 2019
     */
    int insert(BotVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_message_video
     *
     * @mbg.generated Thu Jun 27 23:32:58 CST 2019
     */
    int insertSelective(BotVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_message_video
     *
     * @mbg.generated Thu Jun 27 23:32:58 CST 2019
     */
    BotVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_message_video
     *
     * @mbg.generated Thu Jun 27 23:32:58 CST 2019
     */
    int updateByPrimaryKeySelective(BotVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_message_video
     *
     * @mbg.generated Thu Jun 27 23:32:58 CST 2019
     */
    int updateByPrimaryKey(BotVideo record);
}