package com.zhongweixian.web.mapper;

import com.zhongweixian.web.entity.BotVideo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BotVideoMapper extends BaseMapper<BotVideo> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_message_video
     *
     * @mbg.generated Sat Jun 29 10:53:28 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_message_video
     *
     * @mbg.generated Sat Jun 29 10:53:28 CST 2019
     */
    int insert(BotVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_message_video
     *
     * @mbg.generated Sat Jun 29 10:53:28 CST 2019
     */
    int insertSelective(BotVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_message_video
     *
     * @mbg.generated Sat Jun 29 10:53:28 CST 2019
     */
    BotVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_message_video
     *
     * @mbg.generated Sat Jun 29 10:53:28 CST 2019
     */
    int updateByPrimaryKeySelective(BotVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_message_video
     *
     * @mbg.generated Sat Jun 29 10:53:28 CST 2019
     */
    int updateByPrimaryKey(BotVideo record);

    /**
     * @param hashCode
     * @return
     */
    BotVideo selectByHashCode(@Param("videoSize") Integer videoSize, @Param("hashCode") String hashCode);
}